# Generated by Django 5.0.3 on 2024-03-09 01:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('data', models.CharField(max_length=255, verbose_name='data')),
                ('quantidade', models.DateField(auto_now_add=True)),
                ('calorias', models.CharField(max_length=255, verbose_name='calorias')),
            ],
        ),
    ]
