# Generated by Django 5.0.3 on 2024-03-09 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Factory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=40, verbose_name='descricao')),
                ('calorias', models.CharField(max_length=40, verbose_name='calorias')),
            ],
        ),
        migrations.DeleteModel(
            name='Factory',
        ),
    ]
