# Generated by Django 5.0.3 on 2024-03-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Factory', '0002_factorymodel_delete_factory'),
    ]

    operations = [
        migrations.AddField(
            model_name='factorymodel',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
